classdef FaceRect < robotics.ros.Message
    %FaceRect MATLAB implementation of emotion_intensity/FaceRect
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'emotion_intensity/FaceRect' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'd89b472daab27c7476085359265aedc2' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Height
        Left
        Top
        Width
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'Height', 'Left', 'Top', 'Width'} % List of non-constant message properties
        ROSPropertyList = {'header', 'height', 'left', 'top', 'width'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = FaceRect(msg)
            %FaceRect Construct the message object FaceRect
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'FaceRect', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function height = get.Height(obj)
            %get.Height Get the value for property Height
            height = typecast(int8(obj.JavaMessage.getHeight), 'uint8');
        end
        
        function set.Height(obj, height)
            %set.Height Set the value for property Height
            validateattributes(height, {'numeric'}, {'nonempty', 'scalar'}, 'FaceRect', 'Height');
            
            obj.JavaMessage.setHeight(height);
        end
        
        function left = get.Left(obj)
            %get.Left Get the value for property Left
            left = typecast(int8(obj.JavaMessage.getLeft), 'uint8');
        end
        
        function set.Left(obj, left)
            %set.Left Set the value for property Left
            validateattributes(left, {'numeric'}, {'nonempty', 'scalar'}, 'FaceRect', 'Left');
            
            obj.JavaMessage.setLeft(left);
        end
        
        function top = get.Top(obj)
            %get.Top Get the value for property Top
            top = typecast(int8(obj.JavaMessage.getTop), 'uint8');
        end
        
        function set.Top(obj, top)
            %set.Top Set the value for property Top
            validateattributes(top, {'numeric'}, {'nonempty', 'scalar'}, 'FaceRect', 'Top');
            
            obj.JavaMessage.setTop(top);
        end
        
        function width = get.Width(obj)
            %get.Width Get the value for property Width
            width = typecast(int8(obj.JavaMessage.getWidth), 'uint8');
        end
        
        function set.Width(obj, width)
            %set.Width Set the value for property Width
            validateattributes(width, {'numeric'}, {'nonempty', 'scalar'}, 'FaceRect', 'Width');
            
            obj.JavaMessage.setWidth(width);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Height = obj.Height;
            cpObj.Left = obj.Left;
            cpObj.Top = obj.Top;
            cpObj.Width = obj.Width;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Height = strObj.Height;
            obj.Left = strObj.Left;
            obj.Top = strObj.Top;
            obj.Width = strObj.Width;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Height = obj.Height;
            strObj.Left = obj.Left;
            strObj.Top = obj.Top;
            strObj.Width = obj.Width;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.emotion_intensity.FaceRect.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.emotion_intensity.FaceRect;
            obj.reload(strObj);
        end
    end
end
